---
- name: Configure dhcpcd
  template:
    src={{ item }}.j2
    dest=/etc/{{ item }}
    backup=yes
    owner=root
    group=root
    mode=0644
  loop:
    - dhcpcd.conf
  notify: Restart dhcpcd


- name: Enable and start dhcpcd service
  service:
    name=dhcpcd
    enabled=yes
    state=started
